events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://ib-gateway:5000;
    }

    location /portfolio/ {
      proxy_pass http://pnl-monitor:5001/;
    }

    # Optional: Handle static files for the portfolio app
    location /portfolio/static/ {
      proxy_pass http://pnl-monitor:5001/portfolio/static/;
    }
  }
}
