//@version=5
indicator("Volatility Stop", "VStop", overlay=true, timeframe="", timeframe_gaps=true)

factor = input.float(2.0, "Multiplier", minval = 0.25, step = 0.25)
volStop(close, atrlen, atrfactor) =>
    if not na(close)
        var max     = close
        var min     = close
        var uptrend = true
        var float stop    = na
        atrM        = nz((5) * atrfactor, ta.tr)
        max         := math.max(max, close)
        min         := math.min(min, close)
        stop        := nz(uptrend ? math.max(stop, max - atrM) : math.min(stop, min + atrM), close)
        uptrend     := close - stop >= 0.0
        if uptrend != uptrend[1] and not barstate.isfirst
            max    := close
            min    := close
            stop   := uptrend ? max - atrM : min + atrM
        [stop, uptrend]

[vStop, uptrend] = volStop(close, 20, factor)

plot(vStop, "Volatility Stop", style=plot.style_cross, color= uptrend ? #009688 : #F44336)