// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jengothecat

//@version=5

indicator("Extended‑Hours Volume vs AVOL", overlay=false)


//––– Inputs
AVOL_length = input.int(30, "AVOL Length")
subtractFirstBarVolume = input.bool(true, "Subtract First Bar Volume")

// Get Eanings Per Share Estimate and Earnings Per Share Diluted
EPS_estimate = request.earnings(syminfo.tickerid, earnings.estimate)
EPS_diluted = request.financial(syminfo.tickerid, 'EARNINGS_PER_SHARE_DILUTED', 'FQ')
// Calculate eranings date
Earnings_date = ta.barssince(EPS_estimate - EPS_estimate[1] != 0) == 0

last_bar=session.islastbar
last_reg_bar=session.islastbar_regular
var float pre_eps_volume = na
var float post_eps_volume =na
var earnings_bool = false
var earnigs_avol_sig = false
plotshape(last_reg_bar, "last_reg_bar")
plotshape(last_reg_bar[1], "last_reg_bar[1]")




//––– Daily AVOL via security call (yesterday’s volume)
dVol = request.security(syminfo.tickerid, "D", volume[1], lookahead=barmerge.lookahead_on)
AVOL = ta.sma(dVol, AVOL_length)
var float ehVol =na
//––– Session definitions
inRegular = session.ismarket 
inPre    = session.ispremarket 
inPost   = session.ispostmarket

//––– Pre‑market volume
var float pmVol = 0.0
pmVol := inPre and not inPre[1] ? volume
     : inPre ? pmVol[1] + volume
     : pmVol[1]

//––– After‑hours volume
var float firstPostVol = 0.0
if inPost and not inPost[1]
    firstPostVol := volume
var float ahVol = 0.0
if last_reg_bar
    earnings_bool := false
    earnigs_avol_sig := false
    ahVol := 0.0
    pmVol :=0.0
    ehVol :=0
    post_eps_volume :=na
    pre_eps_volume := na
if Earnings_date
    earnings_bool := true
if not earnings_bool
    ahVol := 0

ahVol:= nz(ahVol[1], 0.0)
ahVol := inPost  and not inPost[1]
         ? (subtractFirstBarVolume ? 0 : volume)
     : inPost 
         ? ahVol[1] + volume - (not inPost[1] and subtractFirstBarVolume ? firstPostVol : 0)
     : ahVol[1]
if not earnings_bool
    ahVol := 0
//––– Combined EH volume (only during pre‑market bars)




if not earnings_bool
    earnigs_avol_sig := false
    ehVol :=0
    post_eps_volume := na
    pre_eps_volume :=na
pmVol_fix = fixnan(pmVol)
ahVol_fix = fixnan(ahVol)


all_vol= ahVol_fix + pmVol_fix
if earnings_bool
    post_eps_volume := ahVol_fix
    pre_eps_volume := pmVol_fix

ehVol := pre_eps_volume + post_eps_volume


//––– %AVOL
pctEH = math.round(ehVol  / AVOL * 100)
pctall_vol =  math.round(all_vol  / AVOL * 100)
pct   = pctEH

plotshape(pct, title="%AVOL", color=color.yellow)
if pct >= 20 or pctall_vol >= 30
    earnigs_avol_sig :=true
bgcolor(earnigs_avol_sig ? color.new(#ddff96, 69) : na)

